name: DevPilot

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
jobs:
  agent:
    if: github.event.label.name == 'devpilot'
    uses: Mohanraj1232/devpilot/.github/workflows/devpilot.yml@main
    secrets:
      DEVPILOT_BOT_TOKEN: ${{ secrets.DEVPILOT_BOT_TOKEN }}
    with:
      issue_number: ${{ github.event.issue.number }}
